<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_COLUMNpadd</name>
   <tag></tag>
   <elementGuidId>695adf48-45e5-4515-9dec-fe1da03dc97d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='workspace']/div[2]/div/article/div/section/div/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>im-column-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLUMNpadding: 16padding: 16padding: 16padding: 16A spectacular titlemargin: 31Hey, you just created a text paragraph! Somebody once said that the pen is mightier than the sword — and that was in 1839. Just imagine, with the power of digital publications and the ability to distribute your content around the world in mere seconds, writing this paragraph could be one of the most influential things you ever do! Click on the gear icon to change the styling of this paragraph, or click and drag the title bar to move it around.margin: 16 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workspace&quot;)/div[2]/div[@class=&quot;css-lga0ph&quot;]/article[1]/div[@class=&quot;css-8xdbwl&quot;]/section[@class=&quot;css-5ehfqj in-viewport scrolling-down&quot;]/div[@class=&quot;css-1mzrgwz comp-section-inner&quot;]/div[@class=&quot;css-18m3bc4 css-nil im-row&quot;]/div[@class=&quot;css-1vy4sqo im-column css-1p0owf7 css-nil css-404dyg&quot;]/div[@class=&quot;im-column-inner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workspace']/div[2]/div/article/div/section/div/div[3]/div[2]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
