<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Noxim me vernica vividi pat quodiu pri fatifect emolta</name>
   <tag></tag>
   <elementGuidId>b3cbf6ec-9546-4503-8102-b91c6f6e7513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='workspace']/div[2]/div/article/div/section/div/div[3]/div[3]/div/div[3]/div[3]/div/div/h4/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Noxim me vernica vividi pat quodiu pri fatifect emolta</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workspace&quot;)/div[2]/div[@class=&quot;css-lga0ph&quot;]/article[1]/div[@class=&quot;css-8xdbwl&quot;]/section[@class=&quot;css-5ehfqj in-viewport scrolling-down&quot;]/div[@class=&quot;css-1mzrgwz comp-section-inner&quot;]/div[@class=&quot;css-18m3bc4 css-nil im-row&quot;]/div[@class=&quot;css-1vy4sqo im-column css-1urdljr css-zb4qwd css-10nut1g&quot;]/div[@class=&quot;im-column-inner&quot;]/div[3]/div[3]/div[1]/div[1]/h4[1]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workspace']/div[2]/div/article/div/section/div/div[2]/div[3]/div/div[3]/div[3]/div/div/h4/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h4/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workspace']/div[2]/div/article/div/section/div/div[3]/div[3]/div/div[3]/div[3]/div/div/h4/span</value>
   </webElementXpaths>
</WebElementEntity>
